---
user: rrossamakhin
my_groups: []

packages:
  # gnome
  - gnome-shell-extensions

  # apps
  - evolution-ews
  - keepassxc
  - wireshark

  # some deps
  - npm # nvim dep
  - ripgrep # nvim dep
  - sshpass # ansible
  - wl-clipboard

  # podman
  - podman
  - podman-compose
  - podman-docker

  # dev
  - golang-go
  - postgresql-client
  - python3-venv

  # network and bluetooth
  - network-manager-openconnect
  - network-manager-openconnect-gnome

  # cli tools
  - bat
  - curl
  - fzf
  - htop
  - krb5-user
  - skopeo
  - sshfs
  - tldr
  - tmux
  - zsh

snap_packages:
  common:
    - beautysh
    - pinta
    - postman
    - ruff
    - telegram-desktop
  classic:
    - pycharm-community

deb:
  - https://github.com/derailed/k9s/releases/download/v0.50.3/k9s_linux_amd64.deb
  - https://github.com/getsops/sops/releases/download/v3.10.2/sops_3.10.2_amd64.deb
  - https://github.com/mkasberg/ghostty-ubuntu/releases/download/1.1.3-0-ppa2/ghostty_1.1.3-0.ppa2_amd64_25.04.deb
  - https://st.ktalk.host/ktalk-app/linux/ktalk3.1.0amd64.deb

fonts:
  - https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Iosevka.zip

bin:
  - url: https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl
    name: kubectl

bin_archived:
  - url: https://github.com/neovim/neovim/releases/download/v0.11.0/nvim-linux-x86_64.tar.gz
    name: nvim
    bin_path: nvim-linux-x86_64/bin/nvim

  - url: https://get.helm.sh/helm-v3.17.0-linux-amd64.tar.gz
    name: helm
    bin_path: linux-amd64/helm

  - url: https://github.com/helmfile/helmfile/releases/download/v0.170.1/helmfile_0.170.1_linux_amd64.tar.gz
    name: helmfile
    bin_path: helmfile

  - url: https://gitlab.com/ilmenshik/pytimesched/-/jobs/3568673400/artifacts/raw/pyTimeSched-v0.6-linux.tar.gz
    name: pyTimeSched
    bin_path: pyTimeSched
    desktop_entity:
      enabled: true
      icon_path: gui/icons/icon.png

dconf:
  # Dock
  - "/org/gnome/shell/extensions/dash-to-dock/click-action": "'minimize'"
  - "/org/gnome/shell/extensions/dash-to-dock/show-trash": "false"

  # Disable window preview when alt-tab
  - "/org/gnome/shell/window-switcher/app-icon-mode": "'app-icon-only'"

  # Keyboard
  - "/org/gnome/desktop/input-sources/xkb-options": "['caps:swapescape']"
  - "/org/gnome/desktop/wm/keybindings/switch-input-source": "['<Alt>Shift_L']"
  - "/org/gnome/desktop/wm/keybindings/close": "['<Shift><Super>q']"
  - "/org/gnome/settings-daemon/plugins/media-keys/home": "['<Super>e']"
  - "/org/gnome/settings-daemon/plugins/media-keys/calculator": "['<Super>c']"

pip:
#  - package_name: aider-chat
#    bin_path: bin/aider
#    symlink_name: aider

  - package_name: uv
    bin_path: bin/uv
    symlink_name: uv

user_systemd_units: []
# - git-sniffer: |-
#     [Unit]
#     Description=git-sniffer
#     [Service]
#     Type=oneshot
#     ExecStart=python %h/.scripts/git-sniffer/main.py %h/places

user_systemd_timers: []
# - git-sniffer: |-
#     [Unit]
#     Description=Run git-sniffer every 10 minute and on boot
#     [Timer]
#     OnBootSec=5min
#     OnUnitActiveSec=10min
#     [Install]
#     WantedBy=timers.target

system_systemd_enabled: []
user_systemd_enabled: []
  # ssh-agent.service,
  # git-sniffer.timer,
  # config-sync.timer,
