---
user: rrossamakhin
my_groups: []

packages:
  # gnome
  - gnome-shell-extensions
  - gnome-tweaks

  # apps
  - alacritty
  - evolution-ews
  - keepassxc
  - obs-studio
  - wireshark

  # some deps
  - npm # nvim dep
  - python3-psutil # ansible gsettings module
  - python3-venv
  - ripgrep # nvim dep
  - sshpass # ansible
  - wl-clipboard

  # dev
  - ansible
  - postgresql-client

  # network and bluetooth
  - network-manager-openconnect
  - network-manager-openconnect-gnome

  # cli tools
  - curl
  - fzf
  - git
  - htop
  - tldr
  - tmux
  - zsh

snap_packages:
  common:
    - beautysh
    - pinta
    - ruff
    - telegram-desktop
  classic:
    - pycharm-community
    - obsidian

deb:
  - https://st.ktalk.host/ktalk-app/linux/ktalk2.13.0amd64.deb
  - https://github.com/derailed/k9s/releases/download/v0.32.7/k9s_linux_amd64.deb
  - https://github.com/getsops/sops/releases/download/v3.9.4/sops_3.9.1_amd64.deb

fonts: []

bin:
  - url: https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl
    name: kubectl

bin_archived:
  - url: https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-arm64.tar.gz
    name: nvim
    bin_path: nvim-linux64/bin/nvim

  - url: https://github.com/JohnnyMorganz/StyLua/releases/download/v2.0.2/stylua-linux-x86_64.zip
    name: stylua
    bin_path: stylua

  - url: https://get.helm.sh/helm-v3.17.0-linux-amd64.tar.gz
    name: helm
    bin_path: linux-amd64/helm

  - url: https://github.com/helmfile/helmfile/releases/download/v0.170.1/helmfile_0.170.1_linux_amd64.tar.gz
    name: helmfile
    bin_path: helmfile

  - url: https://gitlab.com/ilmenshik/pytimesched/-/jobs/3568673400/artifacts/raw/pyTimeSched-v0.6-linux.tar.gz
    name: pyTimeSched
    bin_path: pyTimeSched
    desktop_entity:
      enabled: true
      icon_path: gui/icons/icon.png

dconf:
  # Dock
  - "/org/gnome/shell/extensions/dash-to-dock/click-action": "'minimize'"
  - "/org/gnome/shell/extensions/dash-to-dock/show-trash": "false"

  # Colors
  - "/org/gnome/desktop/interface/gtk-theme": "'Yaru-blue-dark'"
  - "/org/gnome/desktop/interface/icon-theme": "'Yaru-blue'"

  # Keyboard
  - "/org/gnome/desktop/input-sources/xkb-options": "['caps:swapescape']"
  - "/org/gnome/desktop/wm/keybindings/switch-input-source": "['<Alt>Shift_L']"

  # Solid gray wallpaper
  - "/org/gnome/desktop/background/picture-uri": "''"
  - "/org/gnome/desktop/background/picture-uri-dark": "''"
  - "/org/gnome/desktop/background/primary-color": "'#3c3c3c'"

user_systemd_units: []
# - git-sniffer: |-
#     [Unit]
#     Description=git-sniffer
#     [Service]
#     Type=oneshot
#     ExecStart=python %h/.scripts/git-sniffer/main.py %h/places
# - config-sync: |-
#     [Unit]
#     Description=config-sync
#     [Service]
#     Type=oneshot
#     ExecStart=ansible-playbook %h/places/git/personal/ubuntu-bootstrap/ansible/playbooks/sync_home_to_repo.yml

user_systemd_timers: []
# - git-sniffer: |-
#     [Unit]
#     Description=Run git-sniffer every 10 minute and on boot
#     [Timer]
#     OnBootSec=5min
#     OnUnitActiveSec=10min
#     [Install]
#     WantedBy=timers.target
# - config-sync: |-
#     [Unit]
#     Description=Sync configs to repo every 10 minute and on boot
#     [Timer]
#     OnBootSec=5min
#     OnUnitActiveSec=10min
#     [Install]
#     WantedBy=timers.target

system_systemd_enabled: []
user_systemd_enabled: [
  ssh-agent.service,
  # git-sniffer.timer,
  # config-sync.timer,
]
