local u = require("oddsky.utils")
local colors = u.gen_colors()

local hl = u.highlight

local M = {}

M.set = function()
    vim.g.terminal_color_0 = colors.light_1
    vim.g.terminal_color_1 = colors.red_light
    vim.g.terminal_color_2 = colors.green_light
    vim.g.terminal_color_3 = colors.orange_light
    vim.g.terminal_color_4 = colors.blue_light
    vim.g.terminal_color_5 = colors.purple_light
    vim.g.terminal_color_6 = colors.teal_light
    vim.g.terminal_color_7 = colors.light_3
    vim.g.terminal_color_8 = colors.light_5
    vim.g.terminal_color_9 = colors.red_light
    vim.g.terminal_color_10 = colors.green_light
    vim.g.terminal_color_11 = colors.orange_light
    vim.g.terminal_color_12 = colors.blue_light
    vim.g.terminal_color_13 = colors.purple_light
    vim.g.terminal_color_14 = colors.teal_light
    vim.g.terminal_color_15 = colors.light_2
    vim.g.terminal_color_background = colors.light_1
    vim.g.terminal_color_foreground = colors.dark_3

    -- UI highlight
    hl("Normal", { fg = colors.dark_3, bg = colors.light_1 })
    hl("NormalFloat", { fg = colors.dark_3, bg = colors.light_2 })
    hl("FloatBorder", { fg = colors.light_4, bg = colors.light_2 })
    hl("ColorColumn", { bg = colors.light_2 })
    hl("Cursor", { fg = colors.light_4, bg = colors.dark_2 })
    hl("CursorLine", { bg = colors.light_3 })
    hl("CursorColumn", { bg = colors.light_3 })
    hl("Directory", { fg = colors.dark_4, bold = true })
    hl("DiffAdd", { fg = colors.teal_light })
    hl("DiffChange", { fg = colors.orange_light })
    hl("DiffDelete", { fg = colors.red_light })
    hl("DiffText", { fg = colors.orange_light })
    hl("EndOfBuffer", { fg = colors.light_1 })
    hl("ErrorMsg", { fg = colors.red_light, underline = true })
    hl("VertSplit", { fg = colors.light_4 })
    hl("WinSeparator", { link = "VertSplit" })
    hl("Folded", { fg = colors.dark_1 })
    hl("FoldColumn", { fg = colors.dark_1 })
    hl("SignColumn", { fg = colors.dark_2 })
    hl("IncSearch", { fg = colors.dark_4, bg = colors.search_light })
    hl("LineNr", { fg = colors.light_3 })
    hl("CursorLineNr", { fg = colors.light_5 })
    hl("MatchParen", { fg = colors.dark_3, bold = true })
    hl("ModeMsg", { fg = colors.dark_3, bg = colors.light_2 })
    hl("MoreMsg", { fg = colors.dark_3, bg = colors.light_2 })
    hl("NonText", { fg = colors.dark_1 })
    hl("Pmenu", { fg = colors.dark_3, bg = colors.light_2 })
    hl("PmenuSel", { fg = colors.dark_2, bg = colors.light_4 })
    hl("PmenuSbar", { bg = colors.dark_1 })
    hl("PmenuThumb", { bg = colors.light_4 })
    hl("Question", { fg = colors.blue_light })
    hl("Search", { fg = colors.dark_4, bg = colors.search_light })
    hl("SpecialKey", { fg = colors.dark_2 })
    hl("StatusLine", { fg = colors.dark_3, bg = colors.light_2 })
    hl("StatusLineNC", { fg = colors.dark_3, bg = colors.light_3 })
    hl("TabLine", { fg = colors.dark_3, bg = colors.light_3 })
    hl("TabLineFill", { fg = colors.dark_3, bg = colors.light_3 })
    hl("TablineSel", { fg = colors.dark_3, bg = colors.light_1 })
    hl("Title", { bold = true })
    hl("Visual", { bg = colors.visual_light })
    hl("VisualNOS", { bg = colors.visual_light })
    hl("WarningMsg", { fg = colors.yellow_light, bold = true })
    hl("WildMenu", { fg = colors.dark_3, bg = colors.blue_light })
    hl("Comment", { fg = colors.dark_1 })
    hl("Constant", { fg = colors.violet_light })
    hl("String", { fg = colors.teal_light })
    hl("Character", { fg = colors.teal_light })
    hl("Number", { fg = colors.violet_light })
    hl("Boolean", { fg = colors.purple_light })
    hl("Float", { fg = colors.violet_light })
    hl("Identifier", { fg = colors.orange_light })
    hl("Function", { fg = colors.blue_light })
    hl("Statement", { fg = colors.purple_light })
    hl("Conditional", { fg = colors.orange_light, bold = true })
    hl("Repeat", { fg = colors.purple_light })
    hl("Label", { fg = colors.purple_light })
    hl("Operator", { fg = colors.dark_3 })
    hl("Keyword", { fg = colors.orange_light, bold = true })
    hl("Exception", { fg = colors.orange_light })
    hl("PreProc", { fg = colors.violet_light })
    hl("Include", { fg = colors.orange_light, bold = true })
    hl("Define", { fg = colors.yellow_light, bold = true })
    hl("Macro", { fg = colors.yellow_light, bold = true })
    hl("Type", { fg = colors.teal_light, bold = true })
    hl("StorageClass", { fg = colors.teal_light, bold = true })
    hl("Typedef", { fg = colors.teal_light, bold = true })
    hl("Structure", { fg = colors.yellow_light })
    hl("Special", { fg = colors.red_light })
    hl("SpecialChar", { fg = colors.red_light })
    hl("Tag", { fg = colors.teal_light })
    hl("Delimiter", { fg = colors.dark_3 })
    hl("SpecialComment", { fg = colors.dark_1 })
    hl("Debug", { fg = colors.dark_3 })
    hl("Underlined", { underline = true })
    hl("Ignore", { fg = colors.dark_3 })
    hl("Error", { fg = colors.red_light, underline = true })
    hl("Todo", { fg = colors.orange_light, bold = true })
    hl("SpellBad", { fg = colors.red_light, underline = true, sp = colors.red_light })
    hl("SpellCap", { fg = colors.red_light, underline = true, sp = colors.red_light })
    hl("SpellRare", { fg = colors.red_light, underline = true, sp = colors.red_light })
    hl("SpellLocale", { fg = colors.red_light, underline = true, sp = colors.red_light })
    hl("Whitespace", { fg = colors.light_4 })

    --- Treesitter highlight
    hl("@error", { fg = colors.red_light })
    hl("@text.literal", { fg = colors.dark_3 })
    hl("@text.literal.markdown", { fg = colors.dark_3 })
    hl("@text.literal.markdown.inline", { fg = colors.dark_3 })
    hl("@text.title", { fg = colors.teal_light, bold = true })
    hl("@text.emphasis", { italic = true })
    hl("@text.strong", { bold = true })
    hl("@text.uri", { fg = colors.blue_light, underline = true })
    hl("@textReference", { fg = colors.blue_light })
    hl("@text.underline", { underline = true })
    hl("@text.todo", { fg = colors.orange_light, bold = true })
    hl("@text.note", { fg = colors.green_light, bold = true })
    hl("@text.warning", { fg = colors.yellow_light, bold = true })
    hl("@text.danger", { fg = colors.red_light, bold = true })
    hl("@comment", { fg = colors.dark_1, italic = true })
    hl("@punctuation", { fg = colors.dark_3 })
    hl("@punctuation.special", { fg = colors.teal_light })
    hl("@punctuation.bracket", { fg = colors.dark_3 })
    hl("@punctuation.delimiter", { fg = colors.dark_3 })
    hl("@constant", { fg = colors.green_light })
    -- hl("@constant.builtin", { fg = colors.violet_light })
    hl("@constant.macro", { fg = colors.yellow_light, bold = true })
    hl("@define", { fg = colors.yellow_light, bold = true })
    hl("@macro", { fg = colors.yellow_light, bold = true })
    hl("@string", { fg = colors.teal_light })
    hl("@string.escape", { fg = colors.blue_light })
    hl("@stringEscape", { fg = colors.blue_light })
    hl("@string.special", { fg = colors.blue_light })
    hl("@string.regex", { fg = colors.purple_light })
    hl("@character", { fg = colors.teal_light })
    hl("@character.special", { fg = colors.blue_light })
    hl("@number", { fg = colors.violet_light })
    hl("@boolan", { fg = colors.violet_light, bold = true })
    hl("@float", { fg = colors.teal_light })
    hl("@function", { fg = colors.green_light })
    hl("@function.builtin", { fg = colors.blue_light })
    hl("@function.macro", { fg = colors.blue_light, bold = true })
    hl("@attribute", { fg = colors.orange_light })
    hl("@annotation", { fg = colors.yellow_light })
    hl("@parameter", { fg = colors.orange_light })
    hl("@parameter.reference", { fg = colors.orange_light })
    hl("@method", { fg = colors.blue_light })
    hl("@field", { fg = colors.teal_light })
    hl("@property", { fg = colors.blue_light })
    hl("@constructor", { fg = colors.green_light })
    hl("@conditional", { fg = colors.orange_light, bold = true })
    hl("@repeat", { fg = colors.orange_light, bold = true })
    hl("@label", { fg = colors.purple_light })
    hl("@operator", { fg = colors.purple_light })
    hl("@keyword", { fg = colors.red_light })
    hl("@keyword.function", { fg = colors.blue_light })
    hl("@keyword.operator", { fg = colors.orange_light })
    hl("@exception", { fg = colors.orange_light, bold = true })
    hl("@variable", { fg = colors.dark_3 })
    hl("@variable.builtin", { fg = colors.purple_light })
    hl("@variable.parameter", { fg = colors.dark_3 })
    hl("@variable.other", { fg = colors.teal_light })
    hl("@type", { fg = colors.yellow_light })
    hl("@type.builtin", { fg = colors.teal_light })
    hl("@type.qualifire", { fg = colors.teal_light })
    hl("@type.definition", { fg = colors.teal_light, bold = true })
    hl("@storageclass", { fg = colors.orange_light, bold = true })
    hl("@structure", { fg = colors.teal_light, bold = true })
    hl("@namespace", { fg = colors.orange_light })
    hl("@include", { fg = colors.orange_light, bold = true })
    hl("@preproc", { fg = colors.orange_light })
    hl("@debug", { fg = colors.yellow_light })
    hl("@tag", { fg = colors.teal_light })
    hl("@tag.delimiter", { fg = colors.dark_3 })
    hl("@tag.attribute", { fg = colors.orange_light })

    -- python
    hl("@variable.member.python", { fg = colors.blue_light })
    hl("@function.call.python", { fg = colors.green_light })

    -- LSP semantic tokens
    hl("@lsp.type.class", { link = "@type" })
    hl("@lsp.type.decorator", { link = "@function" })
    hl("@lsp.type.enum", { link = "@structure" })
    hl("@lsp.type.enumMember", { link = "@property" })
    hl("@lsp.type.function", { link = "@function" })
    hl("@lsp.type.interface", { link = "@type" })
    hl("@lsp.type.macro", { link = "@macro" })
    hl("@lsp.type.method", { link = "@function" })
    hl("@lsp.type.namespace", { link = "@namespace" })
    hl("@lsp.type.parameter", { link = "@parameter" })
    hl("@lsp.type.property", { link = "@property" })
    hl("@lsp.type.struct", { link = "@structure" })
    hl("@lsp.type.type", { link = "@type" })
    hl("@lsp.type.typeParameter", { link = "@type" })
    hl("@lsp.type.variable", { link = "@variable" })
    hl("@lsp.type.keyword", { link = "@keyword" })

    hl("htmlTag", { fg = colors.teal_light })
    hl("htmlEndTag", { fg = colors.teal_light })
    hl("htmlTagName", { fg = colors.teal_light })
    hl("htmlSpecialTagName", { fg = colors.teal_light })
    hl("htmlArg", { fg = colors.orange_light })

    hl("NvimTreeRootFolder", { fg = colors.dark_3 })
    hl("NvimTreeFolderIcon", { fg = colors.dark_3 })
    hl("NvimTreeFolderName", { fg = colors.dark_3, bold = true })
    hl("NvimTreeEmptyFolderName", { fg = colors.dark_3, bold = true })
    hl("NvimTreeOpenedFolderName", { fg = colors.dark_3, bold = true })
    hl("NvimTreeVertSplit", { fg = colors.light_1 })
    hl("NvimTreeNormal", { bg = colors.light_1 })
    hl("NvimTreeEndOfBuffer", { fg = colors.light_1, bg = colors.light_1 })

    hl("BufferLineIndicatorSelected", { bg = colors.light_1 })
    hl("BufferLineFill", { bg = colors.light_2 })

    -- Telescope nvim
    hl("TelescopePromptBorder", { fg = colors.light_4 })
    hl("TelescopeResultsBorder", { fg = colors.light_4 })
    hl("TelescopePreviewBorder", { fg = colors.light_4 })
    hl("TelescopeNormal", { fg = colors.dark_3 })
    hl("TelescopeSelection", { fg = colors.dark_3 })
    hl("TelescopeMultiSelection", { fg = colors.dark_3 })
    hl("TelescopeMatching", { fg = colors.dark_3, bold = true })
    hl("TelescopePromptPrefix", { fg = colors.dark_3, bold = true })

    hl("LspReferenceText", { bg = colors.blue_light })
    hl("LspReferenceRead", { bg = colors.blue_light })
    hl("LspReferenceWrite", { bg = colors.blue_light })
    hl("DiagnosticError", { fg = colors.red_light })
    hl("DiagnosticWarn", { fg = colors.yellow_light })
    hl("DiagnosticHint", { fg = colors.blue_light })
    hl("DiagnosticInfo", { fg = colors.teal_light })

    hl("CocHighlightText", { bg = colors.blue_light })
    hl("CocHighlightRead", { bg = colors.blue_light })
    hl("CocHighlightWrite", { bg = colors.blue_light })

    hl("CmpItemKind", { fg = colors.dark_3 })

    -- Typescript fix
    hl("typescriptParens", { fg = colors.light_3, bg = "NONE" })
    -- A custome thing to make cmp doc border invisible
    hl("CmpNDocBorder", { fg = colors.light_4, bg = colors.light_1 })

    hl("GitSignsAddLn", { fg = colors.green_light, bg = colors.green_light })
    hl("GitSignsChangeLn", { fg = colors.orange_light, bg = colors.orange_light })
    hl("GitSignsCurrentLineBlame", { fg = colors.dark_2 })

    -- neotree
    hl("NeoTreeDirectoryName", { fg = colors.dark_4 })
    hl("NeoTreeDirectoryIcon", { fg = colors.dark_4 })
    hl("NeoTreeFloatBorder", { fg = colors.light_4, bg = colors.light_1 })
end

return M
