---
- hosts: ubuntu
  gather_facts: true
  tasks:
    - name: Include common role
      import_role:
        name: ubuntu-bootstrap
      tags: ubuntu-bootstrap

    - name: Include docker role
      become: true
      vars:
        docker_install_compose: true
      import_role:
        name: geerlingguy.docker
      tags: docker
