[font]
size = 11.5

[terminal]
shell = "tmux"

[font.normal]
family = "terminal-font"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[window]
decorations = "None"

[keyboard]
bindings = [
    {key = "F11", action = "ToggleFullscreen"},
]

# Campbell flavoured colorscheme

[colors.primary]
background = '#000000'
foreground = '#d9d9d9'

[colors.normal]
black   = '#000000'
red     = '#e61919'
green   = '#3bad1f'
yellow  = '#e5e619'
blue    = '#196be6'
magenta = '#bd19e6'
cyan    = '#5cd6d6'
white   = '#d0d0d0'

[colors.bright]
black   = '#808080'
red     = '#e61919'
green   = '#3bad1f'
yellow  = '#e5e619'
blue    = '#196be6'
magenta = '#bd19e6'
cyan    = '#5cd6d6'
white   = '#FFFFFF'
