[font]
size = 11.5

[font.normal]
family = "JetBrainsMono Nerd Font"

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/tmux"

# [mouse]
# hide_when_typing = true

[window]
decorations = "None"

[colors.primary]
background = '#0c0c0c'
foreground = '#CECECE'

[colors.cursor]
text = '#0E1415'
cursor = '#CECECE'

[colors.normal]
black = '#0E1415'
red = '#e25d56'
green = '#73ca50'
yellow = '#e9bf57'
blue = '#4a88e4'
magenta = '#915caf'
cyan = '#23acdd'
white = '#f0f0f0'

[colors.bright]
black = '#777777'
red = '#f36868'
green = '#88db3f'
yellow = '#f0bf7a'
blue = '#6f8fdb'
magenta = '#e987e9'
cyan = '#4ac9e2'
white = '#FFFFFF'
