import = [
  "~/.config/alacritty/themes/gruvbox_dark.toml",
]

[font]
size = 11.5

[shell]
program = "tmux"

[font.normal]
family = "terminal-font"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[window]
decorations = "None"

[keyboard]
bindings = [
    {key = "F11", action = "ToggleFullscreen"},
]
