[font]
normal = { family = "terminal-font" }
size = 12
[terminal.shell]
program = "tmux"
[env]
TERM = "xterm-256color"
[mouse]
hide_when_typing = true
[window]
decorations_theme_variant = "Dark"
# decorations = "None"
[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
