[font]
size = 12

[shell]
program = "tmux"

[font.normal]
family = "GoMono Nerd Font Mono"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[window]
decorations = "None"

[keyboard]
bindings = [
    {key = "F11", action = "ToggleFullscreen"},
]

# My customized gruvbox
[colors.primary]
background = '#1e1e20'
foreground = '#ded3ba'

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"

[colors.bright]
black = "#75715e"
red = "#f92672"
green = "#a6e22e"
yellow = "#f4bf75"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f9f8f5"
