[font]
size = 12

[shell]
program = "tmux"

[font.normal]
family = "GoMono Nerd Font Mono"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[window]
decorations = "None"

[keyboard]
bindings = [
    {key = "F11", action = "ToggleFullscreen"},
]

# Campbell flavoured colorscheme

# Default colors
[colors.primary]
background = '#0c0c0c'
foreground = '#d9d9d9'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#e61919'
green   = '#3bad1f'
yellow  = '#e5e619'
blue    = '#196be6'
magenta = '#bd19e6'
cyan    = '#19e5e6'
white   = '#d0d0d0'

# Bright colors
[colors.bright]
black   = '#808080'
red     = '#e61919'
green   = '#3bad1f'
yellow  = '#e5e619'
blue    = '#196be6'
magenta = '#bd19e6'
cyan    = '#19e5e6'
white   = '#FFFFFF'
